### ISSUE TITLE
API tomatoes#index ArgumentError

### ISSUE THREAD

**Issue by potomak** [tomatoes-app/tomatoes#298]
```
An ArgumentError occurred in tomatoes#index:

  argument out of range
  app/controllers/api/tomatoes_controller.rb:53:in `from'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.tomato.es/api/tomatoes?from=2017-20-08T01%3A00%3A00Z&to=2017-02-09T01%3A00%3A00Z
  * HTTP Method: GET
  * IP address : 134.17.24.127
  * Parameters : {"from"=>"2017-20-08T01:00:00Z", "to"=>"2017-02-09T01:00:00Z", "controller"=>"api/tomatoes", "action"=>"index"}
  * Timestamp  : 2017-09-03 12:06:55 +0300
  * Server : 24643d7c-a0f2-427c-b559-48a21d80b702
  * Rails root : /app
  * Process: 6

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT_ENCODING                           : gzip,deflate
  * HTTP_CONNECTION                                : close
  * HTTP_CONNECT_TIME                              : 0
  * HTTP_HOST                                      : www.tomato.es
  * HTTP_TOTAL_ROUTE_TIME                          : 0
  * HTTP_USER_AGENT                                : Apache-HttpClient/4.1.1 (java 1.5)
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_VIA                                       : 1.1 vegur
  * HTTP_X_FORWARDED_FOR                           : 134.17.24.127
  * HTTP_X_FORWARDED_PORT                          : 443
  * HTTP_X_FORWARDED_PROTO                         : https
  * HTTP_X_REQUEST_ID                              : 565a4e43-7c80-4daa-9f73-3ce8dbbdbc85
  * HTTP_X_REQUEST_START                           : 1504429615719
  * ORIGINAL_FULLPATH                              : /api/tomatoes?from=2017-20-08T01%3A00%3A00Z&to=2017-02-09T01%3A00%3A00Z
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /api/tomatoes
  * QUERY_STRING                                   : from=2017-20-08T01%3A00%3A00Z&to=2017-02-09T01%3A00%3A00Z
  * REMOTE_ADDR                                    : 10.168.65.231
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /api/tomatoes
  * REQUEST_URI                                    : /api/tomatoes?from=2017-20-08T01%3A00%3A00Z&to=2017-02-09T01%3A00%3A00Z
  * ROUTES_70263111260840_SCRIPT_NAME              :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : www.tomato.es
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : puma 3.8.2 Sassy Salamander
  * action_controller.instance                     : #<Api::TomatoesController:0x007fced13846e8>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007fced24a4b80>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007fced13865d8>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             : marshal
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007fcecdff2078>
  * action_dispatch.logger                         : #<RailsStdoutLogging::StdoutLogger:0x007fcecf7f7b78>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 134.17.24.127
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007fcecfb405f0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=2054636085120634632>]
  * action_dispatch.request.parameters             : {"from"=>"2017-20-08T01:00:00Z", "to"=>"2017-02-09T01:00:00Z", "controller"=>"api/tomatoes", "action"=>"index"}
  * action_dispatch.request.path_parameters        : {:controller=>"api/tomatoes", :action=>"index"}
  * action_dispatch.request.query_parameters       : {"from"=>"2017-20-08T01:00:00Z", "to"=>"2017-02-09T01:00:00Z"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {}
  * action_dispatch.request_id                     : 565a4e43-7c80-4daa-9f73-3ce8dbbdbc85
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x007fcecf933550>
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * http_accept_language.parser                    : #<HttpAcceptLanguage::Parser:0x007fced13a0618>
  * newrelic.transaction_started                   : true
  * puma.config                                    : #<Puma::Configuration:0x007fcecd64d5e0>
  * puma.socket                                    : #<TCPSocket:0x007fced13989e0>
  * rack.after_reply                               : []
  * rack.errors                                    : #<IO:0x007fcecc7ddb18>
  * rack.hijack                                    : #<Puma::Client:0x007fced13989b8>
  * rack.hijack?                                   : true
  * rack.input                                     : #<Puma::NullIO:0x007fceccc75978>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {}
  * rack.request.query_hash                        : {"from"=>"2017-20-08T01:00:00Z", "to"=>"2017-02-09T01:00:00Z"}
  * rack.request.query_string                      : from=2017-20-08T01%3A00%3A00Z&to=2017-02-09T01%3A00%3A00Z
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007fced13a0938>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fced13a08e8>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 3]

-------------------------------
Backtrace:
-------------------------------

  app/controllers/api/tomatoes_controller.rb:53:in `from'
  app/controllers/api/tomatoes_controller.rb:11:in `index'
```

**Comment by andrew-chiz-muzychuk** [comment]
Yes, it would be nice to have error message about wrong date format.
